# Generated by Django 4.0.1 on 2022-01-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='release_dat',
            new_name='release_date',
        ),
    ]
